---
- name: Download Rkt
  get_url: >
   url=https://github.com/coreos/rkt/releases/download/v{{ rkt.debian_version }}/rkt-v{{ rkt.debian_version }}.tar.gz
   dest=/tmp/rkt.zip
# comment hhhhh
- name: Extract Rkt
  unarchive: >
   src=/tmp/rkt.zip
   dest=/opt/
   copy=no
   owner={{ ansible_ssh_user }}
  become: yes
  
- name: Detected RedHat based system
  include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"
- name: install rkt
  yum:
    name: https://github.com/rkt/rkt/releases/download/{{rkt.rpm_version}}/{{rkt.rpm}}
  when: ansible_distribution == "CentOS"

- name: create {{ service_name }} job
  template: src=rkt_runner.service.j2 dest=/etc/systemd/system/{{ service_name }}.service
  register: install_config

- name: notify systemd of config changes
  command: systemctl daemon-reload
  when: install_config.changed == True

- name: start {{ service_name }} and set to start on startup
  service: name={{ service_name }} state=started enabled=yes