---
- name: Download Rkt
  get_url: >
   url=https://github.com/coreos/rkt/releases/download/v{{ rkt.debian_version }}/rkt-v{{ rkt.debian_version }}.tar.gz
   dest=/tmp/rkt.zip

- name: Extract Rkt
  unarchive: >
   src=/tmp/rkt.zip
   dest=/opt/
   copy=no
   owner={{ ansible_ssh_user }}
  become: yes
 
- name: install rkt
  yum:
    name: https://github.com/rkt/rkt/releases/download/{{rkt.rpm_version}}/{{rkt.rpm}}